

#         Powered by TabooLib 6.0         #


Options:
  check-update: true
  data:
    type: SQLite
    source:
      MYSQL:
        host: localhost
        port: 3306
        user: root
        password: root
        database: minecraft