

#         Powered by TabooLib 6.0         #


options:
  check-update: true
  main-level:
    level: 生存等级
    replace-original-level: true
storage:
  type: sqlite
  player-index: uuid
  prefix: faithllevel
  source:
    mysql:
      host: localhost
      port: 3306
      user: root
      password: root
      database: minecraft